from PyQt5 import QtCore, QtGui, QtWidgets
from Register import Register
class ProductList(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(802, 512)
        Form.setStyleSheet("")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setEnabled(False)
        self.tableWidget.setGeometry(QtCore.QRect(0, 110, 801, 1000))
        self.tableWidget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(6, 128, 133, 255), stop:1 rgba(255, 255, 255, 255));\n"
                                        "font: 75 10pt \"MS Shell Dlg 2\";\n"
                                        "color: rgb(0, 0, 0);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setText("عکس")
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.Back = QtWidgets.QPushButton(Form)
        self.Back.setGeometry(QtCore.QRect(10, 10, 40, 40))
        self.Back.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/Registericon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Back.setIcon(icon)
        self.Back.setIconSize(QtCore.QSize(35, 35))
        self.Back.setCheckable(True)
        self.Back.setChecked(True)
        self.Back.setFlat(True)
        self.Back.setObjectName("Back")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(Form)
        self.commandLinkButton.setGeometry(QtCore.QRect(60, 10, 731, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.commandLinkButton.setFont(font)
        self.commandLinkButton.setStyleSheet("background-color: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));\n"
                                            "")
        self.commandLinkButton.setCheckable(True)
        self.commandLinkButton.setChecked(True)
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.commandLinkButton_2 = QtWidgets.QCommandLinkButton(Form)
        self.commandLinkButton_2.setGeometry(QtCore.QRect(60, 60, 731, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.commandLinkButton_2.setFont(font)
        self.commandLinkButton_2.setStyleSheet("background-color: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));")
        self.commandLinkButton_2.setCheckable(True)
        self.commandLinkButton_2.setChecked(True)
        self.commandLinkButton_2.setObjectName("commandLinkButton_2")
        self.AddProducts()
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.Form = Form
        self.Back.clicked.connect(self.BackRegister)

    def BackRegister(self):
        self.Window = QtWidgets.QWidget() 
        self.ui = Register()
        self.ui.setupUi(self.Window)
        self.Window.show()  
        self.Form.close()

    def AddProducts(self):
        _translate = QtCore.QCoreApplication.translate
        Product = open('test.txt','r',encoding="utf-8")
        Product = Product.readlines()
        Product = [P.replace('\n','').split(',') for P in Product]

        for i in range(len(Product)):
            self.tableWidget.setRowCount(i+1)
            item = QtWidgets.QTableWidgetItem()
            item.setText(_translate("Form",str(i+1)))
            self.tableWidget.setVerticalHeaderItem(i,item)
            for j in range(len(Product[i])):
                item = QtWidgets.QTableWidgetItem()
                item.setText(_translate("Form",Product[i][j]))
                self.tableWidget.setItem(i,j,item)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "نام"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form","جنسیت"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "نام خانوادگی"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "شماره تلفن"))

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Product List"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "شناسه فروشنده"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "شناسه محصول"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "میانگین امتیاز"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "قیمت نهایی"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "تخفیف"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "قیمت"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Form", "نام"))
        self.commandLinkButton.setText(_translate("Form", ".کاربر گرامی برای خرید، نظر دادن، ثبت امتیاز و ...  لطفا ابتدا به عنوان مشتری ثبت نام کنید و به صفحه کاربری خود مراجعه کنید"))
        self.commandLinkButton_2.setText(_translate("Form", ".کاربر گرامی برای ارائه محصول جدید لازم است به عنوان فروشنده جدید ثبت نام کنید و به صفحه کاربری خود مراجعه کنید"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = ProductList()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())